### ISSUE TITLE
Simple case

### ISSUE THREAD

**Issue by jaccokrijnen** [chrisdone/haskell-docs#20]
I'm trying to use haskell-docs on a basic use case, but it won't work. Obviously I am missing something simple (I have enabled the documentation flag in my .cabal file).

```
➜  ~  cabal install tagsoup
Resolving dependencies...
Configuring tagsoup-0.13.3...
Building tagsoup-0.13.3...
Installed tagsoup-0.13.3
Updating documentation index /home/jacco/.cabal/share/doc/index.html
➜  ~  haskell-docs Text.HTML.TagSoup parseTags
Couldn't find any packages with that module.
```

Any hints?

(GHC 7.8.4/haddock 2.14.3/Ubuntu 14.04)

**Comment by ivan-m** [comment]
Just to check: are you doing that in a sandbox?

Though in any case, it seems that that incantation wouldn't give you any results:

```
$haskell-docs Text.HTML.TagSoup parseTags
$haskell-docs Text.HTML.TagSoup.Parser parseTags
Package: tagsoup-0.13.3
parseTags
Parse a string to a list of tags, using an HTML 5 compliant parser.
    parseTags "<hello>my&amp;</world>" == [TagOpen "hello" [],TagText "my&",TagClose "world"]
```

**Comment by jaccokrijnen** [comment]
Thanks. No, this is not in a sandbox (although I wonder, is there sandbox support?).

Trying that module gave me different output, though:
```
➜  ~  haskell-docs Text.HTML.TagSoup.Parser parseTags
➜  ~  
```
That is, no output at all.

By the way, Text.HTML.TagSoup re-exports parseTags, so shouldn't it be able to give documentation from there as well?

**Comment by ivan-m** [comment]
As a complete guess, as haskell-docs uses the Haddock files, and `parseTags` isn't listed as being defined in `Text.HTML.TagSoup.Parser` in the Haddock file (just like if you click on "source" it will take you to the source for `.Parser`).

**Comment by jaccokrijnen** [comment]
I do seem to get valid output for types and functions from base, though (GHC 7.8.4, haddock 2.14.3)

**Comment by ivan-m** [comment]
Which version of GHC did you use to build `tagsoup`?

**Comment by jaccokrijnen** [comment]
Also 7.8.4

**Comment by ivan-m** [comment]
Did you rebuild haskell-docs since upgrading GHC?  (It might need to be rebuilt against the new version of Haddock).

**Comment by jaccokrijnen** [comment]
Yes, I did. I also tried cabal installing from the repo, but still the same issue :(

**Comment by jaccokrijnen** [comment]
After some experimenting, I'm fairly certain that only documentation for the global package database is shown (/opt/ghc/7.8.4/lib/ghc-7.8.4/package.conf.d), and not the user database (~/.ghc/x86_64-linux-7.8.4/package.conf.d).
Could this be a haddock version issue?

**Comment by chrisdone** [comment]
Curious. Not sure.

**Comment by chrisdone** [comment]
I think I may have a similar issue. Sometimes the `text` package doesn't yield any results.
