### ISSUE TITLE
GHC 7.10.1 fails to install

### ISSUE THREAD

**Issue by hunteriam** [chrisdone/haskell-docs#23]
Installed haddock-docs
    cabal: InstallPlan: internal error: configured package depends on a non-library package

cabal version 1.22.2.0
cabal-install version 1.22.4.0

**Comment by tejon** [comment]
Same error here, Win7-64, tried inside and outside of a sandbox.

**Comment by vlatkoB** [comment]
Same for ghc 7.10.2

**Comment by evanmeng** [comment]
Got the same problem with ghc 7.10.2, cabal 1.22.2.0 on Mac OS X 10.10.4.

**Comment by funny-code** [comment]
Same for ghc 7.10.2, cabal 1.22.4.0,Mac OS X 10.10.5

**Comment by shssoichiro** [comment]
Same on ghc 7.10.2, cabal 1.22.6, Linux

**Comment by ivan-m** [comment]
I've started work on a fix, hope to have it done early next week.

**Comment by ivan-m** [comment]
I didn't update the matrix in the README for this though.
